import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { requireNodeSqlite } from "../infra/node-sqlite.js";
import type { IssueDependency, Issue, SelfImproveEntry } from "./types.js";

export function resolveProjectSqlitePath(repoPath: string): string {
  return path.join(repoPath, ".openclaw", "project.sqlite");
}

export function initProjectDirectory(repoPath: string): string {
  const dotDir = path.join(repoPath, ".openclaw");
  if (!existsSync(dotDir)) {
    mkdirSync(dotDir, { recursive: true });
  }

  const projectMdPath = path.join(dotDir, "PROJECT.md");
  if (!existsSync(projectMdPath)) {
    writeFileSync(projectMdPath, "# Project Context\n\nGenerated by OpenClaw.\n", "utf-8");
  }

  return path.join(dotDir, "project.sqlite");
}

/** Convert a timestamp value (ISO string or Unix ms number) to Unix ms integer */
function toUnixMs(value: string | number | null | undefined): number | null {
  if (value === null || value === undefined) {
    return null;
  }
  if (typeof value === "number") {
    return value;
  }
  // ISO string
  const ms = new Date(value).getTime();
  return isNaN(ms) ? null : ms;
}

/** Convert a DB row timestamp (INTEGER Unix ms) to number */
function rowTs(value: unknown): number | null {
  if (value === null || value === undefined) {
    return null;
  }
  if (typeof value === "number") {
    return value;
  }
  if (typeof value === "string") {
    // Legacy TEXT ISO string
    const ms = new Date(value).getTime();
    return isNaN(ms) ? null : ms;
  }
  return null;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function mapRowToIssue(row: any): Issue {
  return {
    issueId: row.issue_id,
    title: row.title,
    description: row.description,
    status: row.status,
    severity: row.severity,
    complexity: row.complexity,
    labels: JSON.parse(row.labels || "[]"),
    assignee: row.assignee ?? null,
    projectId: row.project_id ?? null,
    batchId: row.batch_id ?? null,
    requiresApproval: row.requires_approval ?? 0,
    touchesJson: row.touches_json ?? null,
    sourceType: row.source_type ?? "internal",
    sourceExternalId: row.source_external_id ?? null,
    sourceExternalUrl: row.source_external_url ?? null,
    sourceSyncedAt: row.source_synced_at ?? null,
    createdAt: rowTs(row.created_at) ?? Date.now(),
    updatedAt: rowTs(row.updated_at) ?? Date.now(),
    completedAt: rowTs(row.completed_at),
    startedAt: rowTs(row.started_at),
    closedAt: rowTs(row.closed_at),
    approvedAt: rowTs(row.approved_at),
  };
}

export function openProjectDatabase(sqlitePath: string) {
  const { DatabaseSync } = requireNodeSqlite();
  const db = new DatabaseSync(sqlitePath);

  db.exec("PRAGMA journal_mode=WAL");
  db.exec("PRAGMA busy_timeout=5000");

  // Migration: rename backlog → issues if old table exists
  const hasBacklog = db
    .prepare(`SELECT name FROM sqlite_master WHERE type='table' AND name='backlog'`)
    .get();
  const hasIssues = db
    .prepare(`SELECT name FROM sqlite_master WHERE type='table' AND name='issues'`)
    .get();

  if (hasBacklog && !hasIssues) {
    // Migrate from old backlog table to new issues table (schema v2 with Unix ms timestamps)
    db.exec(`
      CREATE TABLE issues (
        issue_id TEXT PRIMARY KEY,
        title TEXT NOT NULL,
        description TEXT NOT NULL DEFAULT '',
        status TEXT NOT NULL DEFAULT 'open',
        severity TEXT NOT NULL DEFAULT 'medium',
        complexity TEXT NOT NULL DEFAULT 'm',
        labels TEXT NOT NULL DEFAULT '[]',
        assignee TEXT,
        project_id TEXT,
        batch_id TEXT,
        requires_approval INTEGER NOT NULL DEFAULT 0,
        touches_json TEXT,
        source_type TEXT NOT NULL DEFAULT 'internal',
        source_external_id TEXT,
        source_external_url TEXT,
        source_synced_at TEXT,
        created_at INTEGER NOT NULL DEFAULT (strftime('%s', 'now') * 1000),
        updated_at INTEGER NOT NULL DEFAULT (strftime('%s', 'now') * 1000),
        completed_at INTEGER,
        started_at INTEGER,
        closed_at INTEGER,
        approved_at INTEGER
      );
    `);
    db.exec(`
      INSERT INTO issues (issue_id, title, description, status, severity, complexity, labels, assignee,
                          source_type, created_at, updated_at, completed_at)
      SELECT task_id, title, description, status, severity, complexity, touches, agent_role,
             'internal',
             CAST((julianday(created_at) - 2440587.5) * 86400000 AS INTEGER),
             CAST((julianday(updated_at) - 2440587.5) * 86400000 AS INTEGER),
             CASE WHEN completed_at IS NOT NULL
               THEN CAST((julianday(completed_at) - 2440587.5) * 86400000 AS INTEGER)
               ELSE NULL END
      FROM backlog;
    `);
    db.exec(`DROP TABLE backlog;`);
  }

  if (!hasBacklog && !hasIssues) {
    db.exec(`
      CREATE TABLE IF NOT EXISTS issues (
        issue_id TEXT PRIMARY KEY,
        title TEXT NOT NULL,
        description TEXT NOT NULL DEFAULT '',
        status TEXT NOT NULL DEFAULT 'open',
        severity TEXT NOT NULL DEFAULT 'medium',
        complexity TEXT NOT NULL DEFAULT 'm',
        labels TEXT NOT NULL DEFAULT '[]',
        assignee TEXT,
        project_id TEXT,
        batch_id TEXT,
        requires_approval INTEGER NOT NULL DEFAULT 0,
        touches_json TEXT,
        source_type TEXT NOT NULL DEFAULT 'internal',
        source_external_id TEXT,
        source_external_url TEXT,
        source_synced_at TEXT,
        created_at INTEGER NOT NULL DEFAULT (strftime('%s', 'now') * 1000),
        updated_at INTEGER NOT NULL DEFAULT (strftime('%s', 'now') * 1000),
        completed_at INTEGER,
        started_at INTEGER,
        closed_at INTEGER,
        approved_at INTEGER
      );
    `);
  }

  // If issues table exists, run incremental column migrations
  if (hasIssues || (!hasBacklog && !hasIssues)) {
    // Add source columns if missing (v1 → v1.1)
    try {
      db.prepare(`SELECT source_type FROM issues LIMIT 1`).get();
    } catch {
      db.exec(`ALTER TABLE issues ADD COLUMN source_type TEXT NOT NULL DEFAULT 'internal';`);
      db.exec(`ALTER TABLE issues ADD COLUMN source_external_id TEXT;`);
      db.exec(`ALTER TABLE issues ADD COLUMN source_external_url TEXT;`);
      db.exec(`ALTER TABLE issues ADD COLUMN source_synced_at TEXT;`);
    }

    // Add v2 columns if missing (v1.x → v2)
    const v2Columns: [string, string][] = [
      ["project_id", "TEXT"],
      ["batch_id", "TEXT"],
      ["requires_approval", "INTEGER NOT NULL DEFAULT 0"],
      ["touches_json", "TEXT"],
      ["started_at", "INTEGER"],
      ["closed_at", "INTEGER"],
      ["approved_at", "INTEGER"],
    ];
    for (const [col, def] of v2Columns) {
      try {
        db.prepare(`SELECT ${col} FROM issues LIMIT 1`).get();
      } catch {
        db.exec(`ALTER TABLE issues ADD COLUMN ${col} ${def};`);
      }
    }

    // Migrate TEXT timestamps to INTEGER Unix ms if they're still strings
    // Detect by checking if created_at looks like an ISO string in any row
    try {
      const sample = db.prepare(`SELECT created_at FROM issues LIMIT 1`).get() as
        | { created_at: unknown }
        | undefined;
      if (sample && typeof sample.created_at === "string") {
        // Still ISO strings — convert all timestamp columns
        db.exec(`
          UPDATE issues SET
            created_at = CAST((julianday(created_at) - 2440587.5) * 86400000 AS INTEGER),
            updated_at = CAST((julianday(updated_at) - 2440587.5) * 86400000 AS INTEGER),
            completed_at = CASE WHEN completed_at IS NOT NULL
              THEN CAST((julianday(completed_at) - 2440587.5) * 86400000 AS INTEGER)
              ELSE NULL END
          WHERE typeof(created_at) = 'text';
        `);
      }
    } catch {
      // No rows or columns don't exist yet — skip
    }
  }

  db.exec(`
    CREATE TABLE IF NOT EXISTS dependencies (
      task_id TEXT NOT NULL,
      depends_on TEXT NOT NULL,
      PRIMARY KEY (task_id, depends_on)
    );
  `);

  db.exec(`
    CREATE TABLE IF NOT EXISTS execution_runs (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      task_id TEXT NOT NULL,
      agent_role TEXT NOT NULL,
      runtime TEXT NOT NULL,
      session_key TEXT,
      label TEXT,
      status TEXT NOT NULL DEFAULT 'running',
      started_at INTEGER NOT NULL DEFAULT (strftime('%s', 'now') * 1000),
      ended_at INTEGER,
      error TEXT,
      commit_hash TEXT
    );
  `);

  db.exec(`
    CREATE TABLE IF NOT EXISTS selfimprove (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      task_id TEXT,
      agent_role TEXT NOT NULL,
      category TEXT NOT NULL DEFAULT 'lesson',
      severity TEXT NOT NULL DEFAULT 'info',
      title TEXT NOT NULL,
      description TEXT NOT NULL,
      tags TEXT,
      scope TEXT NOT NULL DEFAULT 'project',
      applied INTEGER NOT NULL DEFAULT 0,
      created_at INTEGER NOT NULL DEFAULT (strftime('%s', 'now') * 1000)
    );
  `);

  db.exec(`CREATE INDEX IF NOT EXISTS idx_issues_status ON issues(status);`);
  db.exec(`CREATE INDEX IF NOT EXISTS idx_issues_project_id ON issues(project_id);`);
  db.exec(`CREATE INDEX IF NOT EXISTS idx_issues_severity ON issues(severity);`);
  db.exec(`CREATE INDEX IF NOT EXISTS idx_issues_batch_id ON issues(batch_id);`);
  db.exec(
    `CREATE UNIQUE INDEX IF NOT EXISTS idx_issues_external ON issues(source_type, source_external_id) WHERE source_external_id IS NOT NULL;`,
  );
  db.exec(`CREATE INDEX IF NOT EXISTS idx_execution_runs_task_id ON execution_runs(task_id);`);
  db.exec(`CREATE INDEX IF NOT EXISTS idx_selfimprove_task_id ON selfimprove(task_id);`);
  db.exec(
    `CREATE INDEX IF NOT EXISTS idx_selfimprove_category_applied ON selfimprove(category, applied);`,
  );

  const statements = {
    insertIssue: db.prepare(`
      INSERT INTO issues (issue_id, title, description, status, severity, complexity, labels, assignee,
                          project_id, batch_id, requires_approval, touches_json,
                          source_type, source_external_id, source_external_url, source_synced_at,
                          created_at, updated_at, completed_at, started_at, closed_at, approved_at)
      VALUES (@issueId, @title, @description, @status, @severity, @complexity, @labels, @assignee,
              @projectId, @batchId, @requiresApproval, @touchesJson,
              @sourceType, @sourceExternalId, @sourceExternalUrl, @sourceSyncedAt,
              @createdAt, @updatedAt, @completedAt, @startedAt, @closedAt, @approvedAt)
    `),
    getIssue: db.prepare(`SELECT * FROM issues WHERE issue_id = ?`),
    listIssues: db.prepare(`SELECT * FROM issues ORDER BY created_at ASC`),
    listIssuesByProject: db.prepare(
      `SELECT * FROM issues WHERE project_id = ? ORDER BY created_at ASC`,
    ),
    updateIssue: db.prepare(`
      UPDATE issues SET
        title = @title,
        description = @description,
        status = @status,
        severity = @severity,
        complexity = @complexity,
        labels = @labels,
        assignee = @assignee,
        project_id = @projectId,
        batch_id = @batchId,
        requires_approval = @requiresApproval,
        touches_json = @touchesJson,
        source_type = @sourceType,
        source_external_id = @sourceExternalId,
        source_external_url = @sourceExternalUrl,
        source_synced_at = @sourceSyncedAt,
        updated_at = @updatedAt,
        completed_at = @completedAt,
        started_at = @startedAt,
        closed_at = @closedAt,
        approved_at = @approvedAt
      WHERE issue_id = @issueId
    `),
    insertDependency: db.prepare(
      `INSERT OR IGNORE INTO dependencies (task_id, depends_on) VALUES (@taskId, @dependsOn)`,
    ),
    deleteDependency: db.prepare(
      `DELETE FROM dependencies WHERE task_id = @taskId AND depends_on = @dependsOn`,
    ),
    listDependencies: db.prepare(`SELECT * FROM dependencies WHERE task_id = ?`),
    insertSelfImprove: db.prepare(`
      INSERT INTO selfimprove (task_id, agent_role, category, severity, title, description, tags, scope, applied, created_at)
      VALUES (@taskId, @agentRole, @category, @severity, @title, @description, @tags, @scope, @applied, @createdAt)
    `),
    listSelfImprove: db.prepare(`SELECT * FROM selfimprove ORDER BY created_at DESC`),
    getJournalMode: db.prepare(`PRAGMA journal_mode`),
    checkTableExists: db.prepare(`SELECT name FROM sqlite_master WHERE type='table' AND name=?`),
  };

  return {
    db,
    statements,
    addIssue(issue: Issue) {
      const now = Date.now();
      statements.insertIssue.run({
        issueId: issue.issueId,
        title: issue.title,
        description: issue.description,
        status: issue.status,
        severity: issue.severity,
        complexity: issue.complexity,
        labels: JSON.stringify(issue.labels),
        assignee: issue.assignee ?? null,
        projectId: issue.projectId ?? null,
        batchId: issue.batchId ?? null,
        requiresApproval: issue.requiresApproval ?? 0,
        touchesJson: issue.touchesJson ?? null,
        sourceType: issue.sourceType ?? "internal",
        sourceExternalId: issue.sourceExternalId ?? null,
        sourceExternalUrl: issue.sourceExternalUrl ?? null,
        sourceSyncedAt: issue.sourceSyncedAt ?? null,
        createdAt: toUnixMs(issue.createdAt) ?? now,
        updatedAt: toUnixMs(issue.updatedAt) ?? now,
        completedAt: toUnixMs(issue.completedAt) ?? null,
        startedAt: toUnixMs(issue.startedAt) ?? null,
        closedAt: toUnixMs(issue.closedAt) ?? null,
        approvedAt: toUnixMs(issue.approvedAt) ?? null,
      });
    },
    getIssue(issueId: string): Issue | undefined {
      const row = statements.getIssue.get(issueId);
      return row ? mapRowToIssue(row) : undefined;
    },
    listIssues(): Issue[] {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const rows = statements.listIssues.all() as any[];
      return rows.map(mapRowToIssue);
    },
    listIssuesByProject(projectId: string): Issue[] {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const rows = statements.listIssuesByProject.all(projectId) as any[];
      return rows.map(mapRowToIssue);
    },
    updateIssue(issue: Issue) {
      const now = Date.now();
      statements.updateIssue.run({
        issueId: issue.issueId,
        title: issue.title,
        description: issue.description,
        status: issue.status,
        severity: issue.severity,
        complexity: issue.complexity,
        labels: JSON.stringify(issue.labels),
        assignee: issue.assignee ?? null,
        projectId: issue.projectId ?? null,
        batchId: issue.batchId ?? null,
        requiresApproval: issue.requiresApproval ?? 0,
        touchesJson: issue.touchesJson ?? null,
        sourceType: issue.sourceType ?? "internal",
        sourceExternalId: issue.sourceExternalId ?? null,
        sourceExternalUrl: issue.sourceExternalUrl ?? null,
        sourceSyncedAt: issue.sourceSyncedAt ?? null,
        updatedAt: toUnixMs(issue.updatedAt) ?? now,
        completedAt: toUnixMs(issue.completedAt) ?? null,
        startedAt: toUnixMs(issue.startedAt) ?? null,
        closedAt: toUnixMs(issue.closedAt) ?? null,
        approvedAt: toUnixMs(issue.approvedAt) ?? null,
      });
    },
    // Backward-compatible aliases
    addBacklogTask(task: Issue) {
      this.addIssue(task);
    },
    getBacklogTask(taskId: string) {
      return this.getIssue(taskId);
    },
    listBacklogTasks() {
      return this.listIssues();
    },
    updateBacklogTask(task: Issue) {
      this.updateIssue(task);
    },
    addDependency(dependency: IssueDependency) {
      statements.insertDependency.run({
        taskId: dependency.issueId,
        dependsOn: dependency.dependsOn,
      });
    },
    removeDependency(dependency: IssueDependency) {
      statements.deleteDependency.run({
        taskId: dependency.issueId,
        dependsOn: dependency.dependsOn,
      });
    },
    listDependencies(issueId: string): IssueDependency[] {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const rows = statements.listDependencies.all(issueId) as any[];
      return rows.map((row) => ({
        issueId: row.task_id,
        dependsOn: row.depends_on,
      }));
    },
    addSelfImprove(entry: Omit<SelfImproveEntry, "id">) {
      const now = Date.now();
      statements.insertSelfImprove.run({
        taskId: entry.taskId ?? null,
        agentRole: entry.agentRole,
        category: entry.category,
        severity: entry.severity,
        title: entry.title,
        description: entry.description,
        tags: entry.tags ?? null,
        scope: entry.scope,
        applied: entry.applied ? 1 : 0,
        createdAt: toUnixMs(entry.createdAt) ?? now,
      });
    },
    listSelfImprove(): SelfImproveEntry[] {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const rows = statements.listSelfImprove.all() as any[];
      return rows.map((row) => ({
        id: row.id,
        taskId: row.task_id,
        agentRole: row.agent_role,
        category: row.category,
        severity: row.severity,
        title: row.title,
        description: row.description,
        tags: row.tags,
        scope: row.scope,
        applied: Boolean(row.applied),
        createdAt: rowTs(row.created_at) ?? Date.now(),
      }));
    },
    isWalMode(): boolean {
      const result = statements.getJournalMode.get() as { journal_mode: string };
      return result.journal_mode.toLowerCase() === "wal";
    },
    hasTable(tableName: string): boolean {
      return !!statements.checkTableExists.get(tableName);
    },
    addTask(params: {
      taskId?: string;
      issueId?: string;
      title: string;
      description?: string;
      severity?: string;
      complexity?: string;
      touches?: string[];
      labels?: string[];
      agentRole?: string;
      assignee?: string;
      projectId?: string;
      batchId?: string;
      requiresApproval?: boolean;
      touchesJson?: string;
      sourceType?: string;
      sourceExternalId?: string;
      sourceExternalUrl?: string;
      sourceSyncedAt?: string;
    }) {
      const now = Date.now();
      const id = params.issueId || params.taskId || `TASK-${String(Date.now()).slice(-6)}`;
      this.addIssue({
        issueId: id,
        title: params.title,
        description: params.description || "",
        status: "open",
        severity: (params.severity || "medium") as Issue["severity"],
        complexity: (params.complexity || "m") as Issue["complexity"],
        labels: params.labels || params.touches || [],
        assignee: params.assignee || params.agentRole || null,
        projectId: params.projectId || null,
        batchId: params.batchId || null,
        requiresApproval: params.requiresApproval ? 1 : 0,
        touchesJson: params.touchesJson || null,
        sourceType: (params.sourceType || "internal") as Issue["sourceType"],
        sourceExternalId: params.sourceExternalId || null,
        sourceExternalUrl: params.sourceExternalUrl || null,
        sourceSyncedAt: params.sourceSyncedAt || null,
        createdAt: now,
        updatedAt: now,
        completedAt: null,
        startedAt: null,
        closedAt: null,
        approvedAt: null,
      });
    },
    updateTask(taskId: string, updates: Record<string, unknown>) {
      const existing = this.getIssue(taskId);
      if (!existing) {
        throw new Error(`Issue ${taskId} not found`);
      }
      const now = Date.now();
      const updated: Issue = {
        ...existing,
        ...(updates as Partial<Issue>),
        updatedAt: now,
      };
      if (updates.status === "done" && !existing.completedAt) {
        updated.completedAt = now;
      }
      if (updates.status === "in_progress" && !existing.startedAt) {
        updated.startedAt = now;
      }
      if (updates.status === "approved" && !existing.approvedAt) {
        updated.approvedAt = now;
      }
      if ((updates.status === "rejected" || updates.status === "done") && !existing.closedAt) {
        updated.closedAt = now;
      }
      this.updateIssue(updated);
    },
    getSummary(): Record<string, number> {
      const issues = this.listIssues();
      const summary: Record<string, number> = {};
      for (const t of issues) {
        summary[t.status] = (summary[t.status] || 0) + 1;
      }
      summary.total = issues.length;
      return summary;
    },
    getDetailedStats(): {
      statusBreakdown: Record<string, number>;
      severityBreakdown: Record<string, number>;
      complexityBreakdown: Record<string, number>;
      total: number;
      selfImproveUnapplied: number;
      lastActivity: number | null;
      completedLast7d: number;
      completedLast30d: number;
      blockedCritical: Array<{ taskId: string; title: string; severity: string }>;
    } {
      const issues = this.listIssues();
      const statusBreakdown: Record<string, number> = {};
      const severityBreakdown: Record<string, number> = {};
      const complexityBreakdown: Record<string, number> = {};
      let lastActivity: number | null = null;
      let completedLast7d = 0;
      let completedLast30d = 0;
      const now = Date.now();
      const day7 = now - 7 * 86400000;
      const day30 = now - 30 * 86400000;
      const blockedCritical: Array<{ taskId: string; title: string; severity: string }> = [];

      for (const t of issues) {
        statusBreakdown[t.status] = (statusBreakdown[t.status] || 0) + 1;
        if (t.status !== "done" && t.status !== "rejected" && t.status !== "cancelled") {
          severityBreakdown[t.severity] = (severityBreakdown[t.severity] || 0) + 1;
          complexityBreakdown[t.complexity] = (complexityBreakdown[t.complexity] || 0) + 1;
        }
        if (t.updatedAt && (!lastActivity || t.updatedAt > lastActivity)) {
          lastActivity = t.updatedAt;
        }
        if (t.completedAt) {
          if (t.completedAt >= day7) {
            completedLast7d++;
          }
          if (t.completedAt >= day30) {
            completedLast30d++;
          }
        }
        if (
          t.status === "blocked" ||
          (t.status !== "done" &&
            t.status !== "rejected" &&
            t.status !== "cancelled" &&
            (t.severity === "critical" || t.severity === "high"))
        ) {
          blockedCritical.push({ taskId: t.issueId, title: t.title, severity: t.severity });
        }
      }

      const selfImproveEntries = this.listSelfImprove();
      const selfImproveUnapplied = selfImproveEntries.filter((e) => !e.applied).length;

      return {
        statusBreakdown,
        severityBreakdown,
        complexityBreakdown,
        total: issues.length,
        selfImproveUnapplied,
        lastActivity,
        completedLast7d,
        completedLast30d,
        blockedCritical: blockedCritical.slice(0, 10),
      };
    },
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    listTasks(filters?: {
      status?: string;
      severity?: string;
      projectId?: string;
    }): Record<string, unknown>[] {
      let issues = this.listIssues();
      if (filters?.status) {
        issues = issues.filter((t) => t.status === filters.status);
      }
      if (filters?.severity) {
        issues = issues.filter((t) => t.severity === filters.severity);
      }
      if (filters?.projectId) {
        issues = issues.filter((t) => t.projectId === filters.projectId);
      }
      return issues.map((t) => ({
        taskId: t.issueId,
        issueId: t.issueId,
        title: t.title,
        description: t.description,
        status: t.status,
        severity: t.severity,
        complexity: t.complexity,
        touches: t.labels,
        labels: t.labels,
        agentRole: t.assignee,
        assignee: t.assignee,
        projectId: t.projectId,
        batchId: t.batchId,
        requiresApproval: t.requiresApproval,
        touchesJson: t.touchesJson,
        sourceType: t.sourceType,
        sourceExternalId: t.sourceExternalId,
        sourceExternalUrl: t.sourceExternalUrl,
        sourceSyncedAt: t.sourceSyncedAt,
        createdAt: t.createdAt,
        updatedAt: t.updatedAt,
        completedAt: t.completedAt,
        startedAt: t.startedAt,
        closedAt: t.closedAt,
        approvedAt: t.approvedAt,
      }));
    },
    close() {
      db.close();
    },
  };
}
