import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { requireNodeSqlite } from "../infra/node-sqlite.js";
import type { IssueDependency, Issue, SelfImproveEntry } from "./types.js";

export function resolveProjectSqlitePath(repoPath: string): string {
  return path.join(repoPath, ".openclaw", "project.sqlite");
}

export function initProjectDirectory(repoPath: string): string {
  const dotDir = path.join(repoPath, ".openclaw");
  if (!existsSync(dotDir)) {
    mkdirSync(dotDir, { recursive: true });
  }

  const projectMdPath = path.join(dotDir, "PROJECT.md");
  if (!existsSync(projectMdPath)) {
    writeFileSync(projectMdPath, "# Project Context\n\nGenerated by OpenClaw.\n", "utf-8");
  }

  return path.join(dotDir, "project.sqlite");
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function mapRowToIssue(row: any): Issue {
  return {
    issueId: row.issue_id,
    title: row.title,
    description: row.description,
    status: row.status,
    severity: row.severity,
    complexity: row.complexity,
    labels: JSON.parse(row.labels),
    assignee: row.assignee,
    sourceType: row.source_type ?? "internal",
    sourceExternalId: row.source_external_id ?? null,
    sourceExternalUrl: row.source_external_url ?? null,
    sourceSyncedAt: row.source_synced_at ?? null,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    completedAt: row.completed_at,
  };
}

export function openProjectDatabase(sqlitePath: string) {
  const { DatabaseSync } = requireNodeSqlite();
  const db = new DatabaseSync(sqlitePath);

  db.exec("PRAGMA journal_mode=WAL");

  // Migration: rename backlog → issues if old table exists
  const hasBacklog = db
    .prepare(`SELECT name FROM sqlite_master WHERE type='table' AND name='backlog'`)
    .get();
  const hasIssues = db
    .prepare(`SELECT name FROM sqlite_master WHERE type='table' AND name='issues'`)
    .get();

  if (hasBacklog && !hasIssues) {
    // Migrate from old backlog table to new issues table
    db.exec(`
      CREATE TABLE issues (
        issue_id TEXT PRIMARY KEY,
        title TEXT NOT NULL,
        description TEXT NOT NULL DEFAULT '',
        status TEXT NOT NULL DEFAULT 'notStarted',
        severity TEXT NOT NULL DEFAULT 'medium',
        complexity TEXT NOT NULL DEFAULT 'm',
        labels TEXT NOT NULL DEFAULT '[]',
        assignee TEXT,
        source_type TEXT NOT NULL DEFAULT 'internal',
        source_external_id TEXT,
        source_external_url TEXT,
        source_synced_at TEXT,
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        updated_at TEXT NOT NULL DEFAULT (datetime('now')),
        completed_at TEXT
      );
    `);
    db.exec(`
      INSERT INTO issues (issue_id, title, description, status, severity, complexity, labels, assignee, source_type, created_at, updated_at, completed_at)
      SELECT task_id, title, description, status, severity, complexity, touches, agent_role,
             'internal', created_at, updated_at, completed_at
      FROM backlog;
    `);
    db.exec(`DROP TABLE backlog;`);
  }

  if (!hasBacklog && !hasIssues) {
    db.exec(`
      CREATE TABLE IF NOT EXISTS issues (
        issue_id TEXT PRIMARY KEY,
        title TEXT NOT NULL,
        description TEXT NOT NULL DEFAULT '',
        status TEXT NOT NULL DEFAULT 'notStarted',
        severity TEXT NOT NULL DEFAULT 'medium',
        complexity TEXT NOT NULL DEFAULT 'm',
        labels TEXT NOT NULL DEFAULT '[]',
        assignee TEXT,
        source_type TEXT NOT NULL DEFAULT 'internal',
        source_external_id TEXT,
        source_external_url TEXT,
        source_synced_at TEXT,
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        updated_at TEXT NOT NULL DEFAULT (datetime('now')),
        completed_at TEXT
      );
    `);
  }

  // If issues table exists but is missing new columns (e.g. created fresh before migration),
  // add them now
  if (hasIssues && !hasBacklog) {
    // Check if source_type column exists
    try {
      db.prepare(`SELECT source_type FROM issues LIMIT 1`).get();
    } catch {
      db.exec(`ALTER TABLE issues ADD COLUMN source_type TEXT NOT NULL DEFAULT 'internal';`);
      db.exec(`ALTER TABLE issues ADD COLUMN source_external_id TEXT;`);
      db.exec(`ALTER TABLE issues ADD COLUMN source_external_url TEXT;`);
      db.exec(`ALTER TABLE issues ADD COLUMN source_synced_at TEXT;`);
    }
  }

  db.exec(`
    CREATE TABLE IF NOT EXISTS dependencies (
      task_id TEXT NOT NULL,
      depends_on TEXT NOT NULL,
      PRIMARY KEY (task_id, depends_on)
    );
  `);

  db.exec(`
    CREATE TABLE IF NOT EXISTS execution_runs (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      task_id TEXT NOT NULL,
      agent_role TEXT NOT NULL,
      runtime TEXT NOT NULL,
      session_key TEXT,
      label TEXT,
      status TEXT NOT NULL DEFAULT 'running',
      started_at TEXT NOT NULL DEFAULT (datetime('now')),
      ended_at TEXT,
      error TEXT,
      commit_hash TEXT
    );
  `);

  db.exec(`
    CREATE TABLE IF NOT EXISTS selfimprove (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      task_id TEXT,
      agent_role TEXT NOT NULL,
      category TEXT NOT NULL DEFAULT 'lesson',
      severity TEXT NOT NULL DEFAULT 'info',
      title TEXT NOT NULL,
      description TEXT NOT NULL,
      tags TEXT,
      scope TEXT NOT NULL DEFAULT 'project',
      applied INTEGER NOT NULL DEFAULT 0,
      created_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
  `);

  db.exec(`CREATE INDEX IF NOT EXISTS idx_issues_status ON issues(status);`);
  db.exec(
    `CREATE UNIQUE INDEX IF NOT EXISTS idx_issues_external ON issues(source_type, source_external_id) WHERE source_external_id IS NOT NULL;`,
  );
  db.exec(`CREATE INDEX IF NOT EXISTS idx_execution_runs_task_id ON execution_runs(task_id);`);
  db.exec(`CREATE INDEX IF NOT EXISTS idx_selfimprove_task_id ON selfimprove(task_id);`);

  const statements = {
    insertIssue: db.prepare(`
      INSERT INTO issues (issue_id, title, description, status, severity, complexity, labels, assignee, source_type, source_external_id, source_external_url, source_synced_at, created_at, updated_at, completed_at)
      VALUES (@issueId, @title, @description, @status, @severity, @complexity, @labels, @assignee, @sourceType, @sourceExternalId, @sourceExternalUrl, @sourceSyncedAt, @createdAt, @updatedAt, @completedAt)
    `),
    getIssue: db.prepare(`SELECT * FROM issues WHERE issue_id = ?`),
    listIssues: db.prepare(`SELECT * FROM issues ORDER BY created_at ASC`),
    updateIssue: db.prepare(`
      UPDATE issues SET
        title = @title,
        description = @description,
        status = @status,
        severity = @severity,
        complexity = @complexity,
        labels = @labels,
        assignee = @assignee,
        source_type = @sourceType,
        source_external_id = @sourceExternalId,
        source_external_url = @sourceExternalUrl,
        source_synced_at = @sourceSyncedAt,
        updated_at = @updatedAt,
        completed_at = @completedAt
      WHERE issue_id = @issueId
    `),
    insertDependency: db.prepare(
      `INSERT OR IGNORE INTO dependencies (task_id, depends_on) VALUES (@taskId, @dependsOn)`,
    ),
    deleteDependency: db.prepare(
      `DELETE FROM dependencies WHERE task_id = @taskId AND depends_on = @dependsOn`,
    ),
    listDependencies: db.prepare(`SELECT * FROM dependencies WHERE task_id = ?`),
    insertSelfImprove: db.prepare(`
      INSERT INTO selfimprove (task_id, agent_role, category, severity, title, description, tags, scope, applied, created_at)
      VALUES (@taskId, @agentRole, @category, @severity, @title, @description, @tags, @scope, @applied, @createdAt)
    `),
    listSelfImprove: db.prepare(`SELECT * FROM selfimprove ORDER BY created_at DESC`),
    getJournalMode: db.prepare(`PRAGMA journal_mode`),
    checkTableExists: db.prepare(`SELECT name FROM sqlite_master WHERE type='table' AND name=?`),
  };

  return {
    db,
    statements,
    addIssue(issue: Issue) {
      statements.insertIssue.run({
        issueId: issue.issueId,
        title: issue.title,
        description: issue.description,
        status: issue.status,
        severity: issue.severity,
        complexity: issue.complexity,
        labels: JSON.stringify(issue.labels),
        assignee: issue.assignee ?? null,
        sourceType: issue.sourceType ?? "internal",
        sourceExternalId: issue.sourceExternalId ?? null,
        sourceExternalUrl: issue.sourceExternalUrl ?? null,
        sourceSyncedAt: issue.sourceSyncedAt ?? null,
        createdAt: issue.createdAt,
        updatedAt: issue.updatedAt,
        completedAt: issue.completedAt ?? null,
      });
    },
    getIssue(issueId: string): Issue | undefined {
      const row = statements.getIssue.get(issueId);
      return row ? mapRowToIssue(row) : undefined;
    },
    listIssues(): Issue[] {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const rows = statements.listIssues.all() as any[];
      return rows.map(mapRowToIssue);
    },
    updateIssue(issue: Issue) {
      statements.updateIssue.run({
        issueId: issue.issueId,
        title: issue.title,
        description: issue.description,
        status: issue.status,
        severity: issue.severity,
        complexity: issue.complexity,
        labels: JSON.stringify(issue.labels),
        assignee: issue.assignee ?? null,
        sourceType: issue.sourceType ?? "internal",
        sourceExternalId: issue.sourceExternalId ?? null,
        sourceExternalUrl: issue.sourceExternalUrl ?? null,
        sourceSyncedAt: issue.sourceSyncedAt ?? null,
        updatedAt: issue.updatedAt,
        completedAt: issue.completedAt ?? null,
      });
    },
    // Backward-compatible aliases
    addBacklogTask(task: Issue) {
      this.addIssue(task);
    },
    getBacklogTask(taskId: string) {
      return this.getIssue(taskId);
    },
    listBacklogTasks() {
      return this.listIssues();
    },
    updateBacklogTask(task: Issue) {
      this.updateIssue(task);
    },
    addDependency(dependency: IssueDependency) {
      statements.insertDependency.run({
        taskId: dependency.issueId,
        dependsOn: dependency.dependsOn,
      });
    },
    removeDependency(dependency: IssueDependency) {
      statements.deleteDependency.run({
        taskId: dependency.issueId,
        dependsOn: dependency.dependsOn,
      });
    },
    listDependencies(issueId: string): IssueDependency[] {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const rows = statements.listDependencies.all(issueId) as any[];
      return rows.map((row) => ({
        issueId: row.task_id,
        dependsOn: row.depends_on,
      }));
    },
    addSelfImprove(entry: Omit<SelfImproveEntry, "id">) {
      statements.insertSelfImprove.run({
        taskId: entry.taskId ?? null,
        agentRole: entry.agentRole,
        category: entry.category,
        severity: entry.severity,
        title: entry.title,
        description: entry.description,
        tags: entry.tags ?? null,
        scope: entry.scope,
        applied: entry.applied ? 1 : 0,
        createdAt: entry.createdAt,
      });
    },
    listSelfImprove(): SelfImproveEntry[] {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const rows = statements.listSelfImprove.all() as any[];
      return rows.map((row) => ({
        id: row.id,
        taskId: row.task_id,
        agentRole: row.agent_role,
        category: row.category,
        severity: row.severity,
        title: row.title,
        description: row.description,
        tags: row.tags,
        scope: row.scope,
        applied: Boolean(row.applied),
        createdAt: row.created_at,
      }));
    },
    isWalMode(): boolean {
      const result = statements.getJournalMode.get() as { journal_mode: string };
      return result.journal_mode.toLowerCase() === "wal";
    },
    hasTable(tableName: string): boolean {
      return !!statements.checkTableExists.get(tableName);
    },
    addTask(params: {
      taskId?: string;
      issueId?: string;
      title: string;
      description?: string;
      severity?: string;
      complexity?: string;
      touches?: string[];
      labels?: string[];
      agentRole?: string;
      assignee?: string;
      sourceType?: string;
      sourceExternalId?: string;
      sourceExternalUrl?: string;
      sourceSyncedAt?: string;
    }) {
      const now = new Date().toISOString();
      const id = params.issueId || params.taskId || `TASK-${String(Date.now()).slice(-6)}`;
      this.addIssue({
        issueId: id,
        title: params.title,
        description: params.description || "",
        status: "notStarted",
        severity: (params.severity || "medium") as Issue["severity"],
        complexity: (params.complexity || "m") as Issue["complexity"],
        labels: params.labels || params.touches || [],
        assignee: params.assignee || params.agentRole || null,
        sourceType: (params.sourceType || "internal") as Issue["sourceType"],
        sourceExternalId: params.sourceExternalId || null,
        sourceExternalUrl: params.sourceExternalUrl || null,
        sourceSyncedAt: params.sourceSyncedAt || null,
        createdAt: now,
        updatedAt: now,
        completedAt: null,
      });
    },
    updateTask(taskId: string, updates: Record<string, string>) {
      const existing = this.getIssue(taskId);
      if (!existing) {
        throw new Error(`Issue ${taskId} not found`);
      }
      const updated: Issue = {
        ...existing,
        ...updates,
        updatedAt: new Date().toISOString(),
      };
      if (updates.status === "done" && !existing.completedAt) {
        updated.completedAt = new Date().toISOString();
      }
      this.updateIssue(updated);
    },
    getSummary(): Record<string, number> {
      const issues = this.listIssues();
      const summary: Record<string, number> = {};
      for (const t of issues) {
        summary[t.status] = (summary[t.status] || 0) + 1;
      }
      summary.total = issues.length;
      return summary;
    },
    getDetailedStats(): {
      statusBreakdown: Record<string, number>;
      severityBreakdown: Record<string, number>;
      complexityBreakdown: Record<string, number>;
      total: number;
      selfImproveUnapplied: number;
      lastActivity: string | null;
      completedLast7d: number;
      completedLast30d: number;
      blockedCritical: Array<{ taskId: string; title: string; severity: string }>;
    } {
      const issues = this.listIssues();
      const statusBreakdown: Record<string, number> = {};
      const severityBreakdown: Record<string, number> = {};
      const complexityBreakdown: Record<string, number> = {};
      let lastActivity: string | null = null;
      let completedLast7d = 0;
      let completedLast30d = 0;
      const now = Date.now();
      const day7 = now - 7 * 86400000;
      const day30 = now - 30 * 86400000;
      const blockedCritical: Array<{ taskId: string; title: string; severity: string }> = [];

      for (const t of issues) {
        statusBreakdown[t.status] = (statusBreakdown[t.status] || 0) + 1;
        if (t.status !== "done" && t.status !== "cancelled") {
          severityBreakdown[t.severity] = (severityBreakdown[t.severity] || 0) + 1;
          complexityBreakdown[t.complexity] = (complexityBreakdown[t.complexity] || 0) + 1;
        }
        if (t.updatedAt && (!lastActivity || t.updatedAt > lastActivity)) {
          lastActivity = t.updatedAt;
        }
        if (t.completedAt) {
          const completedMs = new Date(t.completedAt).getTime();
          if (completedMs >= day7) {
            completedLast7d++;
          }
          if (completedMs >= day30) {
            completedLast30d++;
          }
        }
        if (
          t.status === "blocked" ||
          (t.status !== "done" &&
            t.status !== "cancelled" &&
            (t.severity === "critical" || t.severity === "high"))
        ) {
          blockedCritical.push({ taskId: t.issueId, title: t.title, severity: t.severity });
        }
      }

      const selfImproveEntries = this.listSelfImprove();
      const selfImproveUnapplied = selfImproveEntries.filter((e) => !e.applied).length;

      return {
        statusBreakdown,
        severityBreakdown,
        complexityBreakdown,
        total: issues.length,
        selfImproveUnapplied,
        lastActivity,
        completedLast7d,
        completedLast30d,
        blockedCritical: blockedCritical.slice(0, 10),
      };
    },
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    listTasks(filters?: { status?: string; severity?: string }): Record<string, unknown>[] {
      let issues = this.listIssues();
      if (filters?.status) {
        issues = issues.filter((t) => t.status === filters.status);
      }
      if (filters?.severity) {
        issues = issues.filter((t) => t.severity === filters.severity);
      }
      return issues.map((t) => ({
        taskId: t.issueId,
        issueId: t.issueId,
        title: t.title,
        description: t.description,
        status: t.status,
        severity: t.severity,
        complexity: t.complexity,
        touches: t.labels,
        labels: t.labels,
        agentRole: t.assignee,
        assignee: t.assignee,
        sourceType: t.sourceType,
        sourceExternalId: t.sourceExternalId,
        sourceExternalUrl: t.sourceExternalUrl,
        sourceSyncedAt: t.sourceSyncedAt,
        createdAt: t.createdAt,
        updatedAt: t.updatedAt,
        completedAt: t.completedAt,
      }));
    },
    close() {
      db.close();
    },
  };
}
