import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { requireNodeSqlite } from "../infra/node-sqlite.js";
import type { BacklogDependency, BacklogTask, SelfImproveEntry } from "./types.js";

export function resolveProjectSqlitePath(repoPath: string): string {
  return path.join(repoPath, ".openclaw", "project.sqlite");
}

export function initProjectDirectory(repoPath: string): string {
  const dotDir = path.join(repoPath, ".openclaw");
  if (!existsSync(dotDir)) {
    mkdirSync(dotDir, { recursive: true });
  }

  const projectMdPath = path.join(dotDir, "PROJECT.md");
  if (!existsSync(projectMdPath)) {
    writeFileSync(projectMdPath, "# Project Context\n\nGenerated by OpenClaw.\n", "utf-8");
  }

  return path.join(dotDir, "project.sqlite");
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function mapRowToBacklogTask(row: any): BacklogTask {
  return {
    taskId: row.task_id,
    title: row.title,
    description: row.description,
    status: row.status,
    severity: row.severity,
    complexity: row.complexity,
    touches: JSON.parse(row.touches),
    agentRole: row.agent_role,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    completedAt: row.completed_at,
  };
}

export function openProjectDatabase(sqlitePath: string) {
  const { DatabaseSync } = requireNodeSqlite();
  const db = new DatabaseSync(sqlitePath);

  db.exec("PRAGMA journal_mode=WAL");

  db.exec(`
    CREATE TABLE IF NOT EXISTS backlog (
      task_id TEXT PRIMARY KEY,
      title TEXT NOT NULL,
      description TEXT NOT NULL DEFAULT '',
      status TEXT NOT NULL DEFAULT 'notStarted',
      severity TEXT NOT NULL DEFAULT 'medium',
      complexity TEXT NOT NULL DEFAULT 'm',
      touches TEXT NOT NULL DEFAULT '[]',
      agent_role TEXT,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now')),
      completed_at TEXT
    );
  `);

  db.exec(`
    CREATE TABLE IF NOT EXISTS dependencies (
      task_id TEXT NOT NULL,
      depends_on TEXT NOT NULL,
      PRIMARY KEY (task_id, depends_on)
    );
  `);

  db.exec(`
    CREATE TABLE IF NOT EXISTS execution_runs (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      task_id TEXT NOT NULL,
      agent_role TEXT NOT NULL,
      runtime TEXT NOT NULL,
      session_key TEXT,
      label TEXT,
      status TEXT NOT NULL DEFAULT 'running',
      started_at TEXT NOT NULL DEFAULT (datetime('now')),
      ended_at TEXT,
      error TEXT,
      commit_hash TEXT
    );
  `);

  db.exec(`
    CREATE TABLE IF NOT EXISTS selfimprove (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      task_id TEXT,
      agent_role TEXT NOT NULL,
      category TEXT NOT NULL DEFAULT 'lesson',
      severity TEXT NOT NULL DEFAULT 'info',
      title TEXT NOT NULL,
      description TEXT NOT NULL,
      tags TEXT,
      scope TEXT NOT NULL DEFAULT 'project',
      applied INTEGER NOT NULL DEFAULT 0,
      created_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
  `);

  db.exec(`CREATE INDEX IF NOT EXISTS idx_backlog_status ON backlog(status);`);
  db.exec(`CREATE INDEX IF NOT EXISTS idx_execution_runs_task_id ON execution_runs(task_id);`);
  db.exec(`CREATE INDEX IF NOT EXISTS idx_selfimprove_task_id ON selfimprove(task_id);`);

  const statements = {
    insertBacklogTask: db.prepare(`
      INSERT INTO backlog (task_id, title, description, status, severity, complexity, touches, agent_role, created_at, updated_at, completed_at)
      VALUES (@taskId, @title, @description, @status, @severity, @complexity, @touches, @agentRole, @createdAt, @updatedAt, @completedAt)
    `),
    getBacklogTask: db.prepare(`SELECT * FROM backlog WHERE task_id = ?`),
    listBacklogTasks: db.prepare(`SELECT * FROM backlog ORDER BY created_at ASC`),
    updateBacklogTask: db.prepare(`
      UPDATE backlog SET
        title = @title,
        description = @description,
        status = @status,
        severity = @severity,
        complexity = @complexity,
        touches = @touches,
        agent_role = @agentRole,
        updated_at = @updatedAt,
        completed_at = @completedAt
      WHERE task_id = @taskId
    `),
    insertDependency: db.prepare(
      `INSERT OR IGNORE INTO dependencies (task_id, depends_on) VALUES (@taskId, @dependsOn)`,
    ),
    deleteDependency: db.prepare(
      `DELETE FROM dependencies WHERE task_id = @taskId AND depends_on = @dependsOn`,
    ),
    listDependencies: db.prepare(`SELECT * FROM dependencies WHERE task_id = ?`),
    insertSelfImprove: db.prepare(`
      INSERT INTO selfimprove (task_id, agent_role, category, severity, title, description, tags, scope, applied, created_at)
      VALUES (@taskId, @agentRole, @category, @severity, @title, @description, @tags, @scope, @applied, @createdAt)
    `),
    listSelfImprove: db.prepare(`SELECT * FROM selfimprove ORDER BY created_at DESC`),
    getJournalMode: db.prepare(`PRAGMA journal_mode`),
    checkTableExists: db.prepare(`SELECT name FROM sqlite_master WHERE type='table' AND name=?`),
  };

  return {
    db,
    statements,
    addBacklogTask(task: BacklogTask) {
      statements.insertBacklogTask.run({
        taskId: task.taskId,
        title: task.title,
        description: task.description,
        status: task.status,
        severity: task.severity,
        complexity: task.complexity,
        touches: JSON.stringify(task.touches),
        agentRole: task.agentRole ?? null,
        createdAt: task.createdAt,
        updatedAt: task.updatedAt,
        completedAt: task.completedAt ?? null,
      });
    },
    getBacklogTask(taskId: string): BacklogTask | undefined {
      const row = statements.getBacklogTask.get(taskId);
      return row ? mapRowToBacklogTask(row) : undefined;
    },
    listBacklogTasks(): BacklogTask[] {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const rows = statements.listBacklogTasks.all() as any[];
      return rows.map(mapRowToBacklogTask);
    },
    updateBacklogTask(task: BacklogTask) {
      statements.updateBacklogTask.run({
        taskId: task.taskId,
        title: task.title,
        description: task.description,
        status: task.status,
        severity: task.severity,
        complexity: task.complexity,
        touches: JSON.stringify(task.touches),
        agentRole: task.agentRole ?? null,
        updatedAt: task.updatedAt,
        completedAt: task.completedAt ?? null,
      });
    },
    addDependency(dependency: BacklogDependency) {
      statements.insertDependency.run({
        taskId: dependency.taskId,
        dependsOn: dependency.dependsOn,
      });
    },
    removeDependency(dependency: BacklogDependency) {
      statements.deleteDependency.run({
        taskId: dependency.taskId,
        dependsOn: dependency.dependsOn,
      });
    },
    listDependencies(taskId: string): BacklogDependency[] {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const rows = statements.listDependencies.all(taskId) as any[];
      return rows.map((row) => ({
        taskId: row.task_id,
        dependsOn: row.depends_on,
      }));
    },
    addSelfImprove(entry: Omit<SelfImproveEntry, "id">) {
      statements.insertSelfImprove.run({
        taskId: entry.taskId ?? null,
        agentRole: entry.agentRole,
        category: entry.category,
        severity: entry.severity,
        title: entry.title,
        description: entry.description,
        tags: entry.tags ?? null,
        scope: entry.scope,
        applied: entry.applied ? 1 : 0,
        createdAt: entry.createdAt,
      });
    },
    listSelfImprove(): SelfImproveEntry[] {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const rows = statements.listSelfImprove.all() as any[];
      return rows.map((row) => ({
        id: row.id,
        taskId: row.task_id,
        agentRole: row.agent_role,
        category: row.category,
        severity: row.severity,
        title: row.title,
        description: row.description,
        tags: row.tags,
        scope: row.scope,
        applied: Boolean(row.applied),
        createdAt: row.created_at,
      }));
    },
    isWalMode(): boolean {
      const result = statements.getJournalMode.get() as { journal_mode: string };
      return result.journal_mode.toLowerCase() === "wal";
    },
    hasTable(tableName: string): boolean {
      return !!statements.checkTableExists.get(tableName);
    },
    addTask(params: {
      taskId: string;
      title: string;
      description?: string;
      severity?: string;
      complexity?: string;
      touches?: string[];
      agentRole?: string;
    }) {
      const now = new Date().toISOString();
      this.addBacklogTask({
        taskId: params.taskId,
        title: params.title,
        description: params.description || "",
        status: "notStarted",
        severity: (params.severity || "medium") as BacklogTask["severity"],
        complexity: (params.complexity || "m") as BacklogTask["complexity"],
        touches: params.touches || [],
        agentRole: params.agentRole || null,
        createdAt: now,
        updatedAt: now,
        completedAt: null,
      });
    },
    updateTask(taskId: string, updates: Record<string, string>) {
      const existing = this.getBacklogTask(taskId);
      if (!existing) {
        throw new Error(`Task ${taskId} not found`);
      }
      const updated: BacklogTask = {
        ...existing,
        ...updates,
        updatedAt: new Date().toISOString(),
      };
      if (updates.status === "done" && !existing.completedAt) {
        updated.completedAt = new Date().toISOString();
      }
      this.updateBacklogTask(updated);
    },
    getSummary(): Record<string, number> {
      const tasks = this.listBacklogTasks();
      const summary: Record<string, number> = {};
      for (const t of tasks) {
        summary[t.status] = (summary[t.status] || 0) + 1;
      }
      summary.total = tasks.length;
      return summary;
    },
    getDetailedStats(): {
      statusBreakdown: Record<string, number>;
      severityBreakdown: Record<string, number>;
      complexityBreakdown: Record<string, number>;
      total: number;
      selfImproveUnapplied: number;
      lastActivity: string | null;
      completedLast7d: number;
      completedLast30d: number;
      blockedCritical: Array<{ taskId: string; title: string; severity: string }>;
    } {
      const tasks = this.listBacklogTasks();
      const statusBreakdown: Record<string, number> = {};
      const severityBreakdown: Record<string, number> = {};
      const complexityBreakdown: Record<string, number> = {};
      let lastActivity: string | null = null;
      let completedLast7d = 0;
      let completedLast30d = 0;
      const now = Date.now();
      const day7 = now - 7 * 86400000;
      const day30 = now - 30 * 86400000;
      const blockedCritical: Array<{ taskId: string; title: string; severity: string }> = [];

      for (const t of tasks) {
        statusBreakdown[t.status] = (statusBreakdown[t.status] || 0) + 1;
        if (t.status !== "done" && t.status !== "cancelled") {
          severityBreakdown[t.severity] = (severityBreakdown[t.severity] || 0) + 1;
          complexityBreakdown[t.complexity] = (complexityBreakdown[t.complexity] || 0) + 1;
        }
        if (t.updatedAt && (!lastActivity || t.updatedAt > lastActivity)) {
          lastActivity = t.updatedAt;
        }
        if (t.completedAt) {
          const completedMs = new Date(t.completedAt).getTime();
          if (completedMs >= day7) {
            completedLast7d++;
          }
          if (completedMs >= day30) {
            completedLast30d++;
          }
        }
        if (
          t.status === "blocked" ||
          (t.status !== "done" &&
            t.status !== "cancelled" &&
            (t.severity === "critical" || t.severity === "high"))
        ) {
          blockedCritical.push({ taskId: t.taskId, title: t.title, severity: t.severity });
        }
      }

      const selfImproveEntries = this.listSelfImprove();
      const selfImproveUnapplied = selfImproveEntries.filter((e) => !e.applied).length;

      return {
        statusBreakdown,
        severityBreakdown,
        complexityBreakdown,
        total: tasks.length,
        selfImproveUnapplied,
        lastActivity,
        completedLast7d,
        completedLast30d,
        blockedCritical: blockedCritical.slice(0, 10),
      };
    },
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    listTasks(filters?: { status?: string; severity?: string }): Record<string, unknown>[] {
      let tasks = this.listBacklogTasks();
      if (filters?.status) {
        tasks = tasks.filter((t) => t.status === filters.status);
      }
      if (filters?.severity) {
        tasks = tasks.filter((t) => t.severity === filters.severity);
      }
      return tasks.map((t) => ({
        taskId: t.taskId,
        title: t.title,
        description: t.description,
        status: t.status,
        severity: t.severity,
        complexity: t.complexity,
        touches: t.touches,
        agentRole: t.agentRole,
        createdAt: t.createdAt,
        updatedAt: t.updatedAt,
        completedAt: t.completedAt,
      }));
    },
    close() {
      db.close();
    },
  };
}
